#!/bin/bash

# Quick Setup Script for Google Sign-In Web
# This script helps you set up Google Sign-In for Flutter web

echo "🚀 SmartHealth Google Sign-In Web Setup"
echo "======================================="
echo ""
echo "❌ CURRENT ISSUE: ClientID not set for web authentication"
echo ""
echo "✅ SOLUTION: Follow these steps:"
echo ""
echo "1️⃣  Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "2️⃣  Create OAuth 2.0 Client ID for Web Application"
echo "   - Application type: Web application"
echo "   - Authorized JavaScript origins: http://localhost:3000"
echo ""
echo "3️⃣  Copy the Web Client ID (format: xxxxx.apps.googleusercontent.com)"
echo ""
echo "4️⃣  Update these files with your Client ID:"
echo "   📁 lib/config/google_config.dart"
echo "   📁 web/index.html"
echo ""
echo "5️⃣  Replace 'YOUR_WEB_CLIENT_ID' with your actual Client ID"
echo ""
echo "6️⃣  Run: flutter clean && flutter pub get && flutter run -d chrome"
echo ""
echo "💡 Need help? Check GOOGLE_SIGNIN_SETUP.md for detailed instructions"
echo ""
echo "🔧 Current configuration status:"
echo "   ❌ Web Client ID: NOT_CONFIGURED"
echo "   ❌ HTML meta tag: NOT_CONFIGURED" 
echo "   ✅ Dart code: READY"
echo "   ✅ Auto-refresh: READY (2-minute interval)"